
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  recyclingchain.com:
    external:
      name: recyclingchain_network

services:

  explorerdb.recyclingchain.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.recyclingchain.com
    hostname: explorerdb.recyclingchain.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - recyclingchain.com

  explorer.recyclingchain.com:
    image: hyperledger/explorer:latest
    container_name: explorer.recyclingchain.com
    hostname: explorer.recyclingchain.com
    environment:
      - DATABASE_HOST=explorerdb.recyclingchain.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=true
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../network/organizations:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.recyclingchain.com:
        condition: service_healthy
    networks:
      - recyclingchain.com
